[package]
name = "probe-svc"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
windows-service = "0.8"
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security", "Win32_System_Services", "Win32_System_Threading"] }

[[bin]]
name = "probe-svc"
path = "src/main.rs"

[[bin]]
name = "notify-probe"
path = "src/notify.rs"

[[bin]]
name = "notify2"
path = "src/notify2.rs"

[[bin]]
name = "probe3"
path = "src/probe3.rs"
